version: 0.2

env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "{{s3_bucket_url}}"
    BUILD_FOLDER: "dist"
    CLOUDFRONT_DISTRIBUTION_ID: "{{E1BX3QLR3K2ARH}}"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli

  build:
    commands:
      - echo Build started
      - ng build
      
   post_build:
    commands:
      - echo Deploying to S3 bucket...
      - aws s3 sync $BUILD_FOLDER/ s3://$S3_BUCKET/ --delete --cache-control $CACHE_CONTROL
      - echo Invalidating CloudFront cache...
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
    
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
  discard-paths: yes
